# Generated by Django 5.1.4 on 2026-04-14 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('THREE_MONTH', '3 Months'), ('SIX_MONTH', '6 Months'), ('ONE_YEAR', '1 Year')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('utr_number', models.CharField(blank=True, help_text='UTR / Transaction reference number (optional)', max_length=50)),
                ('screenshot', models.ImageField(upload_to='upi_screenshots/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UPI Payment Request',
                'verbose_name_plural': 'UPI Payment Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
